"""
VeriDoc — Pydantic Schemas for API Request and Response Validation (Phase 8)
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# -----------------------------------------------------------------------------
# System & Health Schemas
# -----------------------------------------------------------------------------

class HealthResponse(BaseModel):
    """Response model for API health status."""
    status: str = Field(default="healthy", description="Current health status of the API")
    service: str = Field(default="VeriDoc API", description="Service name")
    version: str = Field(default="0.1.0", description="API version")
    is_document_indexed: bool = Field(default=False, description="Whether a document is currently indexed in the vector store")


# -----------------------------------------------------------------------------
# Document Management Schemas
# -----------------------------------------------------------------------------

class DocumentUploadResponse(BaseModel):
    """Response model for document upload and ingestion."""
    filename: str = Field(..., description="Original filename of the uploaded PDF")
    total_pages: int = Field(..., description="Total number of extracted pages")
    total_characters: int = Field(..., description="Total character count across all pages")
    total_chunks: int = Field(..., description="Number of text chunks created and indexed")
    indexed_vectors: int = Field(..., description="Number of vectors stored in FAISS")
    status: str = Field(default="success", description="Processing status")
    message: str = Field(default="Document successfully processed and indexed in FAISS.", description="Status message")


class DocumentStatsResponse(BaseModel):
    """Response model for current document and vector store statistics."""
    document_name: Optional[str] = Field(None, description="Name of the currently indexed document")
    total_pages: int = Field(0, description="Total pages in the document")
    total_characters: int = Field(0, description="Total character count")
    total_chunks: int = Field(0, description="Total chunks in the document")
    indexed_vectors: int = Field(0, description="Total vectors indexed in FAISS")
    is_ready: bool = Field(False, description="Whether the pipeline is ready for questions")


# -----------------------------------------------------------------------------
# Question & Answering Schemas
# -----------------------------------------------------------------------------

class QuestionRequest(BaseModel):
    """Request model for asking questions."""
    question: str = Field(..., min_length=1, description="Natural language question to ask about the document")
    top_k: Optional[int] = Field(default=5, ge=1, le=20, description="Number of relevant chunks to retrieve")


class SourceCitation(BaseModel):
    """Represents an individual source citation accompanying a generated answer."""
    chunk_id: int = Field(..., description="Unique sequential chunk ID")
    page_number: int = Field(..., description="1-indexed source page number in the PDF")
    document_name: str = Field(..., description="Source document filename")
    char_count: int = Field(..., description="Character count of the chunk")
    text: str = Field(..., description="Chunk text content used as context")
    similarity_score: float = Field(..., description="Cosine similarity score from FAISS retrieval")


class QuestionResponse(BaseModel):
    """Response model for grounded answer generation."""
    question: str = Field(..., description="The user question that was asked")
    answer: str = Field(..., description="Grounded answer generated by the LLM")
    sources: List[SourceCitation] = Field(default_factory=list, description="Source citations and retrieved chunks")
